# Generated by Django 3.1.13 on 2021-09-03 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q', models.TextField()),
                ('A', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=1000)),
                ('Message', models.TextField()),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='LastSearchedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(default='RENTYUG')),
            ],
        ),
        migrations.CreateModel(
            name='MessageBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=2000)),
                ('MessagePartner', models.CharField(max_length=2000)),
                ('UnreadMessages', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SendBy', models.CharField(max_length=2000)),
                ('Message', models.TextField()),
                ('RecievedBy', models.CharField(max_length=2000)),
                ('DateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='postImages')),
                ('HasImage', models.BooleanField()),
                ('Tittle', models.TextField()),
                ('Media', models.FileField(blank=True, upload_to='Posts')),
                ('Text', models.TextField()),
                ('TotalLikes', models.IntegerField(default=0)),
                ('Activated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostCommentsReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=1000)),
                ('Reply', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=900)),
                ('Message', models.TextField()),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Image', models.ImageField(upload_to='catagoryImages')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalHits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TotalHitsPerPersonPerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=1000)),
                ('Hits', models.IntegerField(default=0)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.FloatField(default=3)),
                ('MainImage', models.ImageField(upload_to='serviceMainImages')),
                ('ShopName', models.CharField(max_length=3000)),
                ('PriceType', models.CharField(max_length=300)),
                ('OpenTime', models.CharField(max_length=300)),
                ('closeTime', models.CharField(max_length=300)),
                ('Description', models.TextField(default='Description box is empty.')),
                ('VStatus', models.BooleanField(default=False)),
                ('RentalStatus', models.BooleanField(default=True)),
                ('NoOfItems', models.IntegerField(default=1)),
                ('Address', models.TextField(default='0')),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('Activated', models.BooleanField(default=True)),
                ('Posts', models.ManyToManyField(blank=True, to='core.Post')),
                ('RatedBy', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('SearchNames', models.ManyToManyField(blank=True, to='core.SearchName')),
                ('ServiceFeedback', models.ManyToManyField(blank=True, to='core.ServiceFeedback')),
                ('ServiceImages', models.ManyToManyField(blank=True, to='core.Images')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicescatagory')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.TextField()),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('MobileNo', models.CharField(max_length=20)),
                ('Rating', models.FloatField(default=5)),
                ('LastSearcheTag', models.TextField(default='RENTYUG')),
                ('LastSearchNotFound', models.TextField(default='RENTYUG')),
                ('Image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.images')),
                ('LastCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicescatagory')),
                ('LastProductTags', models.ManyToManyField(blank=True, to='core.SearchName')),
                ('LastSearchedTags', models.ManyToManyField(blank=True, to='core.LastSearchedTag')),
                ('SavedServices', models.ManyToManyField(blank=True, related_name='_profile_SavedServices_+', to='core.Service')),
                ('Service', models.ManyToManyField(blank=True, to='core.Service')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=1000)),
                ('Comment', models.TextField()),
                ('Replies', models.ManyToManyField(blank=True, to='core.PostCommentsReplies')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Comments',
            field=models.ManyToManyField(blank=True, to='core.PostComments'),
        ),
        migrations.AddField(
            model_name='post',
            name='LikedBy',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanName', models.CharField(max_length=900)),
                ('Description', models.TextField()),
                ('Rate', models.CharField(max_length=500)),
                ('Open', models.BooleanField(default=False)),
                ('PlanServices', models.ManyToManyField(blank=True, to='core.Service')),
            ],
        ),
        migrations.CreateModel(
            name='InterestedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Services', models.ManyToManyField(blank=True, to='core.Service')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FrontPageFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default='Normal', max_length=100)),
                ('Feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.feedbacks')),
            ],
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='Image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.images'),
        ),
    ]
