# Generated by Django 3.1.13 on 2021-10-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210916_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emailConfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='emailNotification',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='noOfTimeGiveItems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='noOfTimeTakeItems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='noOfTimeRented',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='images',
            name='Image',
            field=models.ImageField(default='images/rentyug.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='MobileNo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.FloatField(default=23),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lng',
            field=models.FloatField(default=77),
        ),
        migrations.AlterField(
            model_name='service',
            name='Address',
            field=models.TextField(default='Bhopal'),
        ),
        migrations.AlterField(
            model_name='service',
            name='lat',
            field=models.FloatField(default=23),
        ),
        migrations.AlterField(
            model_name='service',
            name='lng',
            field=models.FloatField(default=77),
        ),
    ]
