# Generated by Django 3.1.13 on 2021-10-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211001_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.FloatField(default=23.25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lng',
            field=models.FloatField(default=77.41),
        ),
        migrations.AlterField(
            model_name='service',
            name='lat',
            field=models.FloatField(default=23.25),
        ),
        migrations.AlterField(
            model_name='service',
            name='lng',
            field=models.FloatField(default=77.41),
        ),
    ]
